### PR TITLE
issue-63

### LINKED ISSUE #63: After updating the plugin, the site is getting crashed.
**Describe the bug**
After updating your plugin Custom Order Numbers for Woocommerce we had a major database crash. Fortunately our host support managed to place back an older version and our webshop was accesable again after half an hour. We have been using your plugin for some time now and where very happy and satisfied. 

. FYI this is the culprit query that took done one of our shops:
SELECT SQL_CALC_FOUND_ROWS  wp_posts.* FROM wp_posts  LEFT JOIN wp_postmeta ON (wp_posts.ID = wp_postmeta.post_id AND wp_postmeta.meta_key = '_alg_wc_custom_order_number' )  LEFT JOIN wp_postmeta AS mt1 ON (wp_posts.ID = mt1.post_id AND mt1.meta_key = '_alg_wc_custom_order_number_meta_key_updated' ) WHERE 1=1  AND (
  wp_postmeta.post_id IS NULL
  AND
  mt1.post_id IS NULL
) AND wp_posts.post_type = 'shop_order' AND ((wp_posts.post_status <> 'trash' AND wp_posts.post_status <> 'auto-draft')) GROUP BY wp_posts.ID ORDER BY wp_posts.post_date DESC LIMIT 0, 5000

**Additional context**
https://tychesoftwares.freshdesk.com/a/tickets/30738

### PR DESCRIPTION
**Pull request by Shasvat7**
Changed the post limit in the SQL query to 1 from 5000 on admin_init hook, which was crashing the DB.

Fixes #63

### CODE REVIEW

File: custom-order-numbers-for-woocommerce/includes/class-alg-wc-custom-order-numbers-core.php [hunk 1]
```diff
@@ -271,7 +287,23 @@ public function alg_custom_order_numbers_update_old_custom_order_numbers_callbac
...
+						'key'     => '_alg_wc_custom_order_number',
+						'compare' => 'NOT EXISTS',
+					),
+					array(
+						'key'     => '_alg_wc_custom_order_number_meta_key_updated',
+						'compare' => 'NOT EXISTS',
+					),
+				),
+			);
+			$loop_orders = new WP_Query( $args );
```
Comment (ashokrane) [inline custom-order-numbers-for-woocommerce/includes/class-alg-wc-custom-order-numbers-core.php:306]: If this code block is repeated twice, can we not create a function for it?

**Review by ashokrane — APPROVED** [review]
