### PR TITLE
issue-47

### LINKED ISSUE #47: The order number is missing, the woo_order page shows only prefix after the update.
**Describe the bug**
The order number is missing, the woo_order page shows only prefix after the update.  

**To Reproduce**
1. When Order numbers counter set as Order ID. https://www.screencast.com/t/B2nesr1ECaU
2. Placed an order
3. Go to woo order page and I noticed that only prefix appear not custom order number
https://www.screencast.com/t/5X2uISaJ

**Expected behavior**
Woo order id should be displayed with the prefix 

2 clients have reported the same issue. 
https://tychesoftwares.freshdesk.com/a/tickets/27490
https://tychesoftwares.freshdesk.com/a/tickets/27496

### PR DESCRIPTION
**Pull request by Shasvat7**
The only prefix was coming and the order number was not coming in the new orders. This is fixed now

Fixes #47

### CODE REVIEW

File: custom-order-numbers-for-woocommerce/includes/class-alg-wc-custom-order-numbers-core.php [hunk 1]
```diff
@@ -590,6 +590,24 @@ public function display_order_number( $order_number, $order ) {
 			$order_timestamp       = strtotime( ( $is_wc_version_below_3 ? $order->order_date : $order->get_date_created() ) );
 			if ( 'yes' !== get_option( 'alg_custom_order_numbers_show_admin_notice', '' ) || 'yes' === get_option( 'alg_custom_order_numbers_no_old_orders_to_update', '' ) ) {
 				$order_number_meta = get_post_meta( $order_id, '_alg_wc_full_custom_order_number', true );
+				if ( 'yes' !== get_post_meta( $order_id, 'new_orders_updated', true ) ) {
```
Comment (ashokrane) [inline custom-order-numbers-for-woocommerce/includes/class-alg-wc-custom-order-numbers-core.php:593]: Please add a comment here on why this block of code has been added.

**Review by ashokrane — APPROVED** [review]
